language: gl
footermenu: Páxinas
footercontact: Contacto
menu:
    -
        name: Inicio
        description: Páxina de inicio
        type: redirect
        url: /gl
    -
        name: Weblog
        description: Weblog
        type: node
        url: /es/blog
    -
        name: Comunidade
        description: Comunidade
        type: page
        url: community
    -
        name: Descarga
        description: Descargar e-cidadania
        type: page
        url: download
    -
        name: Desenvolvemento
        description: Trac e-cidadania
        type: redirect
        url: http://dev.ecidadania.org
    -
        name: Documentación
        description: Documentación de e-cidadania
        type: redirect
        url: http://docs.ecidadania.org
    -
        name: Demostración
        description: Demostración de e-cidadania
        type: page
        url: demo
extra_pages:
    -
        name: Colaboradores
        description: Equipo e colaboradores
        type: page
        url: team
    -
        name: Cidadania
        description: Web de cidadania
        type: redirect
        url: http://cidadania.coop
    -
        name: Historia
        description: Historia
        type: page
        url: history
contact_links:
    -
        name: Listas de correo
        description: Listas de correo
        type: page
        url: mailing
    -
        name: Incidencias
        description: Incidencias e problemas
        type: redirect
        url: http://dev.ecidadania.org
    -
        name: Soporte
        description: Axuda e soporte
        type: redirect
        url: mailto:support@ecidadania.org
