language: es
footermenu: Páginas
footercontact: Contacto
menu:
    -
        name: Inicio
        description: Página de inicio
        type: redirect
        url: /es/
    -
        name: Weblog
        description: Weblog
        type: node
        url: http://blog.ecidadania.org
    -
        name: Comunidad
        description: Comunidad
        type: page
        url: community
    -
        name: Descarga
        description: Descargar e-cidadania
        type: page
        url: download
    -
        name: Desarrollo
        description: Trac e-cidadania
        type: redirect
        url: http://code.ecidadania.org
    -
        name: Documentación
        description: Documentación de e-cidadania
        type: redirect
        url: http://docs.ecidadania.org
    -
        name: Demostración
        description: Demostración de e-cidadania
        type: page
        url: http://demo.ecidadania.org
extra_pages:
    -
        name: Colaboradores
        description: Equipo y colaboradores
        type: page
        url: team
    -
        name: Cidadania
        description: Web de cidadania
        type: redirect
        url: http://cidadania.coop
contact_links:
    -
        name: Listas de correo e iRC
        description: Listas de correo e iRC
        type: page
        url: mailing
    -
        name: Incidencias
        description: Incidencias y problemas
        type: redirect
        url: http://code.ecidadania.org
    -
        name: Soporte
        description: Ayuda y soporte
        type: redirect
        url: mailto:info@ecidadania.org
